# Generated by Django 4.2.2 on 2023-10-19 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('digito_ver', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('apellido_pat', models.CharField(max_length=30)),
                ('apellido_mate', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('nombre_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_masc', models.CharField(max_length=30)),
                ('especie', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('tamanio', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('nombre_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_mascota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacunas', models.IntegerField()),
                ('ac_fisica', models.CharField(max_length=1)),
                ('comida_tiempo', models.IntegerField()),
                ('tiene_sintomas', models.CharField(max_length=1)),
                ('sintomas', models.CharField(max_length=20)),
                ('tiene_enfermedad', models.CharField(max_length=1)),
                ('enferme_ante', models.CharField(max_length=20)),
                ('tiene_alergias', models.CharField(max_length=1)),
                ('alergias', models.CharField(max_length=15)),
                ('tiene_operaciones', models.CharField(max_length=1)),
                ('operaciones', models.CharField(max_length=2)),
                ('nombre_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_formulario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.CharField(max_length=150)),
                ('nombre_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_comentario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('informacion', models.CharField(max_length=800)),
                ('categoria', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('nombre_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
