# Generated by Django 4.2.2 on 2023-10-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persona_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default='perfil/default.png', null=True, upload_to='perfil'),
        ),
    ]
