# Generated by Django 4.2.2 on 2023-10-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_persona_apellido_mate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default='perfil/default.png', null=True, upload_to='perfil'),
        ),
    ]
