# Generated by Django 4.2.2 on 2023-10-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_persona_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido_mate',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido_pat',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primer_nombre',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='segundo_nombre',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
    ]
