# Generated by Django 4.2.5 on 2023-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_persona_apellido_pat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default='perfil/default.png', null=True, upload_to='media/perfil'),
        ),
    ]
