# Generated by Django 4.2.2 on 2023-11-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_persona_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dinamico',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
