# Generated by Django 4.2.2 on 2023-11-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_persona_dinamico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.CharField(choices=[('1', 'Perro'), ('2', 'Gato'), ('3', 'Alimentación'), ('4', 'Adopción')], default='1', max_length=2),
        ),
    ]
