# Generated by Django 4.2.2 on 2023-11-04 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_blog_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='nombre_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
