# Generated by Django 4.2.2 on 2023-11-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_blog_likes_comentario_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
