# Generated by Django 4.2.2 on 2023-11-10 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_blog_like_comentario_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nombre_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comentario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mascota', to=settings.AUTH_USER_MODEL),
        ),
    ]
