# Generated by Django 4.2.2 on 2023-11-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_comentario_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animal', models.CharField(default='Perro', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(default='Perro', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_raza', models.CharField(default='Chihuahua', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='like',
            new_name='is_like',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='edad',
            new_name='anio_nac',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='genero',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='tamanio',
        ),
        migrations.AddField(
            model_name='mascota',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animal_mascota', to='core.animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_post', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raza_mascota', to='core.raza'),
        ),
    ]
