# Generated by Django 4.2.2 on 2023-11-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_animal_categoria_raza_rename_like_blog_is_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.blog')),
            ],
        ),
    ]
