# Generated by Django 4.2.2 on 2023-11-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_imagenblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenBlog',
        ),
    ]
