# Generated by Django 4.2.2 on 2023-11-22 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_mascota_animal_raza_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='core.mascota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='perfil/default.png', null=True, upload_to='fotos'),
        ),
    ]
