# Generated by Django 4.2.2 on 2023-11-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_formulario_mascota_alter_mascota_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
