# Generated by Django 4.2.5 on 2023-12-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_formulario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alergia',
        ),
    ]
